theme: jekyll-theme-slate
title: Welcome to Seattle DOT's Working Draft of the Transportation Information Infrastructure Plan
description: This is a work in progress. Bookmark us if you want to watch us develop this plan over the next 4-6 months. 
