theme: jekyll-theme-slate
title: Transportation Information Infrastructure Plan (DRAFT)
description: Welcome to Seattle DOT's _Working Draft_ of the **Transportation Information Infrastructure Plan.** This is a work in progress. Bookmark us if you want to watch us develop this plan over the next 4-6 months. 
